services:
  init:
    image: alpine
    entrypoint: install -d -o ${NAS_UID:?} -g ${NAS_GID:?} -m 770
    volumes:
      - ${PATH_TO_ROOT:?}/caddy:/tmp/caddy
    command:
      - /tmp/caddy/data
      - /tmp/caddy/config

  # https://hub.docker.com/_/caddy/tags
  caddy:
    image: caddy:2.9.1-alpine
    container_name: caddy
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    environment:
      HOST_INTERNAL: ${HOST_INTERNAL:?}
    volumes:
      - ${PATH_TO_ROOT:?}/caddy/data:/data
      - ${PATH_TO_ROOT:?}/caddy/config:/config
      - ${PATH_TO_ROOT:?}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      init:
        condition: service_completed_successfully

networks:
  proxy:
    external: true
