# yaml-language-server: $schema=https://www.schemastore.org/traefik-v3-file-provider.json

http:
  routers:
    cockpit:
      service: cockpit
      rule: Host(`cockpit.{{env `ROOT_DOMAIN`}}`)
      entryPoints:
        - local-secure
  services:
    cockpit:
      loadBalancer:
        servers:
          - url: https://localhost:9090
