services:
  # https://hub.docker.com/r/portainer/portainer-ce/tags
  portainer:
    image: portainer/portainer-ce:2.29.0
    container_name: portainer
    restart: unless-stopped
    command: -H tcp://admin-docker-socket:2375
    networks:
      - admin-docker-socket
    ports:
      - 9000:9000
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
    labels:
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$

networks:
  admin-docker-socket:
    external: true
