{
 "title": "System (Prometheus)",
 "description": "System metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "cpu_cores",
    "query": {
     "query": "query_result(scalar(machine_cpu_cores))"
    }
   },
   {
    "name": "mem_total",
    "query": {
     "query": "query_result(scalar(ceil(node_memory_MemTotal_bytes / 1024 / 1024 / 1024)))"
    }
   },
   {
    "name": "swap_total",
    "query": {
     "query": "query_result(scalar(ceil(node_memory_SwapTotal_bytes / 1024 / 1024 / 1024)))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[30s])))",
     "legendFormat": "CPU ($cpu_cores cores)"
    },
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "RAM ($mem_total GB)"
    },
    {
     "expr": "100 * (1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes))",
     "legendFormat": "SWAP ($swap_total GB)"
    }
   ]
  },
  {
   "title": "Mountpoint usage",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - node_filesystem_avail_bytes / node_filesystem_size_bytes)",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Containers UP",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(time() - container_last_seen{image!=\"\"} < 30)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Core {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Usage % (per container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(irate(container_cpu_usage_seconds_total{image!=\"\"}[$__rate_interval]) / scalar(machine_cpu_cores)) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes - node_memory_SReclaimable_bytes",
     "legendFormat": "RAM"
    },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "RAM Usage (per container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\"}) by(name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "(R) {{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "(W) {{device}}"
    }
   ]
  },
  {
   "title": "Disk I/O (per container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{image!=\"\"}[$__rate_interval])) by (name, device)",
     "legendFormat": "(R) {{device}}: {{name}}"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{image!=\"\"}[$__rate_interval])) by (name, device)",
     "legendFormat": "(W) {{device}}: {{name}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * rate(node_network_receive_bytes_total[$__rate_interval])",
     "legendFormat": "Rx {{device}}"
    },
    {
     "expr": "8 * rate(node_network_transmit_bytes_total[$__rate_interval])",
     "legendFormat": "Tx {{device}}"
    }
   ]
  },
  {
   "title": "Network Traffic (per container)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "8 * sum(rate(container_network_receive_bytes_total{image!=\"\"}[$__rate_interval])) by (name)",
     "legendFormat": "Rx {{name}}"
    },
    {
     "expr": "8 * sum(rate(container_network_transmit_bytes_total{image!=\"\"}[$__rate_interval])) by (name)",
     "legendFormat": "Tx {{name}}"
    }
   ]
  },
  {
   "title": "CPU Temp °C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=~\"platform_coretemp.*\"} * on (chip, sensor) group_left (label) node_hwmon_sensor_label",
     "legendFormat": "{{label}}"
    }
   ]
  },
  {
   "title": "Disk Temp °C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "expr": "smartctl_device_temperature{temperature_type=\"current\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "S.M.A.R.T. (Overview)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "max(smartctl_device) by (device, model_name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_capacity_bytes) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_power_on_seconds) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_smart_status) by (device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S.M.A.R.T. (NVMe)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "max(smartctl_device_available_spare) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_bytes_read) by (device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_bytes_written) by(device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_critical_warning) by(device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_media_errors) by(device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_num_err_log_entries) by(device)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartctl_device_percentage_used) by(device)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S.M.A.R.T. (SATA)",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "max(smartctl_device_attribute{attribute_value_type=\"raw\", attribute_name=~\"Offline_Uncorrectable|Reallocated_Sector_Ct|Spin_Up_Time|Raw_Read_Error_Rate|Spin_Retry_Count|Reallocated_Event_Count|Current_Pending_Sector|Seek_Error_Rate\"}) by (device, attribute_name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}