services:
  # https://github.com/linuxserver/docker-duckdns/pkgs/container/duckdns
  duckdns:
    image: ghcr.io/linuxserver/duckdns:version-a6c167e0
    container_name: duckdns
    restart: unless-stopped
    environment:
      PUID: ${NAS_UID:?}
      PGID: ${NAS_GID:?}
      TZ: ${TZ:?}
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINS:?}
      TOKEN: ${DUCKDNS_TOKEN:?}
      UPDATE_IP: ipv4
      LOG_FILE: false
    volumes:
      - ${PATH_TO_ROOT:?}/duckdns/config:/config
