services:
  # https://github.com/linuxserver/docker-duckdns/pkgs/container/duckdns
  # https://github.com/linuxserver/docker-duckdns/releases
  duckdns:
    image: ghcr.io/linuxserver/duckdns:version-bdcb41e5
    container_name: duckdns
    restart: unless-stopped
    environment:
      PUID: ${NAS_UID:?}
      PGID: ${NAS_GID:?}
      TZ: ${TZ:?}
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINS:?}
      TOKEN: ${DUCKDNS_TOKEN:?}
      UPDATE_IP: ipv4
      LOG_FILE: false
    volumes:
      - ./config:/config

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: br-${COMPOSE_PROJECT_NAME:?}
