#!/usr/bin/env sh

max_attempts=30
sleep_seconds=5

if ! docker info >/dev/null 2>&1; then
    echo "ERROR: Docker daemon is not available"
    exit 1
fi

if [ "$#" -eq 0 ]; then
    echo "Usage: $(basename $0) <container1> [container2 ...]"
    exit 1
fi

for container_name in "$@"; do
    echo "Waiting for container '$container_name'..."

    i=1

    while [ "$i" -le "$max_attempts" ]; do
        if docker inspect $container_name >/dev/null 2>&1; then
            status=$(
                docker inspect $container_name -f '
                    {{- if .State.Health -}}
                        {{- .State.Health.Status -}}
                    {{- else -}}
                        {{- .State.Status -}}
                    {{- end -}}
                ' 2>/dev/null
            )

            if [ "$status" = "healthy" ] || [ "$status" = "running" ]; then
                echo "Container '$container_name' is $status"
                echo # New line
                break
            fi

            echo "Attempt $i/$max_attempts: container '$container_name' is $status"
        else
            echo "Attempt $i/$max_attempts: container '$container_name' not found"
        fi

        i=$((i + 1))

        sleep $sleep_seconds
    done

    if [ "$i" -gt "$max_attempts" ]; then
        echo "ERROR: Container '$container_name' did not become running/healthy"
        exit 1
    fi
done

echo "All containers are running/healthy"
