server:
  port: 80
  database: /home/filebrowser/data/database.db
  cacheDir: /home/filebrowser/cache
  cacheDirCleanup: true
  disableUpdateCheck: true
  sources:
    - path: /srv
  filesystem:
    createFilePermission: 660
    createDirectoryPermission: 770
  logging:
    - output: stdout
      levels: info|warning|error
      apiLevels: disabled

frontend:
  disableUsedPercentage: true

userDefaults:
  editorQuickSave: true
  showHidden: true
  preview:
    popup: false
  fileLoading:
    uploadChunkSizeMb: 50
  permissions:
    modify: true
    delete: true
    create: true

auth:
  methods:
    password:
      enabled: false
    oidc:
      enabled: true
      clientId: ${OIDC_CLIENT_ID}
      clientSecret: ${OIDC_CLIENT_SECRET}
      issuerUrl: https://authelia.${ROOT_DOMAIN}
      scopes: email openid profile groups
      userIdentifier: preferred_username
      adminGroup: admins
      createUser: false
