services:
  # https://github.com/linuxserver/docker-speedtest-tracker/pkgs/container/speedtest-tracker
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:1.4.2
    container_name: speedtest_tracker
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ${PATH_TO_ROOT:?}/speedtest-tracker/data:/config
    environment:
      PUID: ${NAS_UID:?}
      PGID: ${NAS_GID:?}
      TZ: ${TZ:?}
      APP_KEY: ${APP_KEY:?}
      DATETIME_FORMAT: j M Y, G:i:s
      DISPLAY_TIMEZONE: ${TZ:?}
      DB_CONNECTION: sqlite
      SPEEDTEST_SCHEDULE: 0 */2 * * *
      PRUNE_RESULTS_OLDER_THAN: 7
    labels:
      - traefik.enable=true
      - traefik.http.routers.speedtest-tracker.entrypoints=local-secure
      - traefik.http.routers.speedtest-tracker.rule=Host(`speedtest.${ROOT_DOMAIN:?}`)
      - traefik.http.services.speedtest-tracker.loadbalancer.server.port=80

networks:
  proxy:
    external: true
