services:
  init:
    image: localhost/homelab-init:v1
    pull_policy: never
    entrypoint: create-dirs
    environment:
      NAS_UID: ${NAS_UID:?}
      NAS_GID: ${NAS_GID:?}
    volumes:
      - ./:/tmp/navidrome
      - ${PATH_TO_MEDIA:?}:/tmp/media
    command:
      - /tmp/navidrome/data
      - /tmp/media
      - /tmp/media/music

  # https://github.com/navidrome/navidrome/pkgs/container/navidrome
  # https://github.com/navidrome/navidrome/releases
  navidrome:
    image: ghcr.io/navidrome/navidrome:0.61.1
    container_name: navidrome
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    environment:
      ND_CONFIGFILE: /navidrome.yml
    volumes:
      - ./data:/data
      - ./navidrome.yml:/navidrome.yml:ro
      - ${PATH_TO_MEDIA:?}/music:/music:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      glance.icon: di:navidrome
      glance.url: https://navidrome.${ROOT_DOMAIN:?}
      glance.category: media

      traefik.enable: true

      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
    depends_on:
      init:
        condition: service_completed_successfully

networks:
  default:
    name: navidrome
    driver_opts:
      com.docker.network.bridge.name: br-navidrome
