http:
  routers:
    admin:
      entryPoints:
        - local-secure
      rule: Host(`admin.{{env `ROOT_DOMAIN`}}`)
      service: admin
  services:
    admin:
      loadBalancer:
        servers:
          - url: "{{env `NAS_URL`}}"
  middlewares:
    security-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        referrerPolicy: no-referrer
        forceSTSHeader: true
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        customResponseHeaders:
          Content-Security-Policy: frame-ancestors https://*.{{env `ROOT_DOMAIN`}}
