services:
  init:
    image: alpine
    entrypoint: install -d -o ${NAS_UID:?} -g ${NAS_GID:?} -m 770
    volumes:
      - ./:/tmp/traefik
    command:
      - /tmp/traefik/letsencrypt

  # https://hub.docker.com/_/traefik/tags
  # https://github.com/traefik/traefik/releases
  traefik:
    image: traefik:v3.4.4
    container_name: traefik
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    extra_hosts:
      host.docker.internal: host-gateway
    networks:
      - proxy
      - readonly-docker-socket
    command:
      - --api.dashboard
      - --api.insecure

      - --log.level=${LOG_LEVEL:?}

      - --entrypoints.local.address=:80
      - --entrypoints.local.http.redirections.entrypoint.to=local-secure
      - --entrypoints.local.http.middlewares=security-headers@file

      - --entrypoints.local-secure.address=:443
      - --entrypoints.local-secure.asDefault=true
      - --entrypoints.local-secure.http.middlewares=security-headers@file
      - --entrypoints.local-secure.http.tls.certResolver=duckdns-resolver
      - --entrypoints.local-secure.http.tls.domains[0].main=*.${ROOT_DOMAIN:?}

      - --entrypoints.external.address=:81
      - --entrypoints.external.http.redirections.entrypoint.to=local-secure # 81 -> 443 -> 444 (by router)
      - --entrypoints.external.http.middlewares=security-headers@file

      - --entrypoints.external-secure.address=:444
      - --entrypoints.external-secure.http.middlewares=security-headers@file
      - --entrypoints.external-secure.http.tls.certResolver=duckdns-resolver
      - --entrypoints.external-secure.http.tls.domains[0].main=*.${ROOT_DOMAIN:?}

      - --serversTransport.insecureSkipVerify

      - --providers.docker.endpoint=tcp://readonly-docker-socket:2375
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy
      - --providers.docker.defaultRule=Host(`{{ coalesce (index .Labels "traefik.custom.host") (index .Labels "com.docker.compose.service") }}.${ROOT_DOMAIN:?}`)

      - --providers.file.directory=/dynamic-conf

      - --certificatesResolvers.duckdns-resolver.acme.email=${ACME_EMAIL:?}
      - --certificatesResolvers.duckdns-resolver.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.duckdns-resolver.acme.dnsChallenge.provider=duckdns
    environment:
      ROOT_DOMAIN: ${ROOT_DOMAIN:?}
      DUCKDNS_TOKEN: ${DUCKDNS_TOKEN:?}
    ports:
      - 80:80
      - 81:81
      - 443:443
      - 444:444
    dns:
      - 1.1.1.1
      - 8.8.8.8
    volumes:
      - ./letsencrypt:/letsencrypt
      - ./dynamic-conf:/dynamic-conf:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      traefik.http.services.traefik-dashboard.loadbalancer.server.port: 8080
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
    depends_on:
      init:
        condition: service_completed_successfully

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: br-${COMPOSE_PROJECT_NAME:?}
  proxy:
    external: true
  readonly-docker-socket:
    external: true
