services:
  # https://github.com/gethomepage/homepage/pkgs/container/homepage
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.1.1
    container_name: homepage
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: ${NAS_UID:?}
      PGID: ${NAS_GID:?}
      TZ: ${TZ:?}
      HOMEPAGE_ALLOWED_HOSTS: homepage.${ROOT_DOMAIN:?}
      HOMEPAGE_VAR_ROOT_DOMAIN: ${ROOT_DOMAIN:?}
      HOMEPAGE_VAR_JELLYFIN_API_KEY: ${JELLYFIN_API_KEY:?}
      HOMEPAGE_VAR_AUDIOBOOKSHELF_API_KEY: ${AUDIOBOOKSHELF_API_KEY:?}
      HOMEPAGE_VAR_NEXTCLOUD_API_KEY: ${NEXTCLOUD_API_KEY:?}
      HOMEPAGE_VAR_RADARR_API_KEY: ${RADARR_API_KEY:?}
      HOMEPAGE_VAR_SONARR_API_KEY: ${SONARR_API_KEY:?}
      HOMEPAGE_VAR_LIDARR_API_KEY: ${LIDARR_API_KEY:?}
      HOMEPAGE_VAR_PROWLARR_API_KEY: ${PROWLARR_API_KEY:?}
      HOMEPAGE_VAR_BESZEL_USERNAME: ${BESZEL_USERNAME:?}
      HOMEPAGE_VAR_BESZEL_PASSWORD: ${BESZEL_PASSWORD:?}
      HOMEPAGE_VAR_BESZEL_SYSTEM_NAME: ${BESZEL_SYSTEM_NAME:?}
    volumes:
      - ${PATH_TO_ROOT:?}/homepage/config:/app/config
      - ${PATH_TO_ROOT:?}/homepage/images:/app/public/images
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.entrypoints=local-secure
      - traefik.http.routers.homepage.rule=Host(`homepage.${ROOT_DOMAIN:?}`)
      - traefik.http.services.homepage.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
