services:
  init:
    image: alpine
    entrypoint: chmod -R g+w
    volumes:
      - ./:/tmp/homepage
    command:
      - /tmp/homepage/config
      - /tmp/homepage/images

  # https://github.com/gethomepage/homepage/pkgs/container/homepage
  # https://github.com/gethomepage/homepage/releases
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.4.0
    container_name: homepage
    restart: unless-stopped
    networks:
      - proxy
      - readonly-docker-socket
    environment:
      PUID: ${NAS_UID:?}
      PGID: ${NAS_GID:?}
      TZ: ${TZ:?}
      HOMEPAGE_ALLOWED_HOSTS: homepage.${ROOT_DOMAIN:?}
      HOMEPAGE_VAR_ROOT_DOMAIN: ${ROOT_DOMAIN:?}
    volumes:
      - ./config:/app/config
      - ./images:/app/public/images
    labels:
      traefik.enable: true
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
    depends_on:
      init:
        condition: service_completed_successfully

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: br-${COMPOSE_PROJECT_NAME:?}
  proxy:
    external: true
  readonly-docker-socket:
    external: true
