services:
  # https://github.com/nicotsx/zerobyte/pkgs/container/zerobyte
  # https://github.com/nicotsx/zerobyte/releases
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.29.2
    container_name: zerobyte
    restart: unless-stopped
    environment:
      APP_SECRET: ${APP_SECRET:?}
      BASE_URL: https://zerobyte.${ROOT_DOMAIN:?}
      TZ: ${TZ:?}
    volumes:
      - ./data:/var/lib/zerobyte
      - ..:/mydata/homelab:ro
      - ${PATH_TO_MEDIA:?}:/mydata/media:ro
      - ${PATH_TO_FILES:?}:/mydata/files:ro
      - ${PATH_TO_BACKUPS:?}:/var/lib/zerobyte/repositories
      - /etc/localtime:/etc/localtime:ro
    labels:
      glance.icon: di:zerobyte.png
      glance.url: https://zerobyte.${ROOT_DOMAIN:?}
      glance.category: admin

      traefik.enable: true

      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:?}
    driver_opts:
      com.docker.network.bridge.name: br-${COMPOSE_PROJECT_NAME:?}
