services:
  init:
    image: alpine
    entrypoint: install -d -o ${NAS_UID:?} -g ${NAS_GID:?} -m 770
    volumes:
      - ./:/tmp/dockge
    command:
      - /tmp/dockge/data

  # https://hub.docker.com/r/louislam/dockge/tags
  dockge:
    image: louislam/dockge:1.5.0
    container_name: dockge
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    networks:
      - admin-docker-socket
    ports:
      - 5001:5001
    env_file:
      - ${PATH_TO_ROOT:?}/global.env
    environment:
      DOCKGE_STACKS_DIR: ${PATH_TO_ROOT:?}
      DOCKER_HOST: tcp://admin-docker-socket:2375
      DOCKER_BUILDKIT: 0
    volumes:
      - ./data:/app/data
      - ${PATH_TO_ROOT:?}:${PATH_TO_ROOT:?}:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
    depends_on:
      init:
        condition: service_completed_successfully

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: br-${COMPOSE_PROJECT_NAME:?}
  admin-docker-socket:
    external: true
