services:
  # https://hub.docker.com/r/nicolargo/glances/tags
  glances:
    image: nicolargo/glances:4.3.1
    container_name: glances
    restart: unless-stopped
    pid: host
    networks:
      - proxy
    environment:
      GLANCES_OPT: -w
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.glances.entrypoints=local-secure
      - traefik.http.routers.glances.rule=Host(`glances.${ROOT_DOMAIN:?}`)
      - traefik.http.services.glances.loadbalancer.server.port=61208

networks:
  proxy:
    external: true
