services:
  init:
    image: localhost/homelab-init:v1
    pull_policy: never
    entrypoint: create-dirs
    environment:
      NAS_UID: ${NAS_UID:?}
      NAS_GID: ${NAS_GID:?}
    volumes:
      - ./:/tmp/whats-up-docker
    command:
      - /tmp/whats-up-docker/data

  # https://github.com/getwud/wud/pkgs/container/wud
  # https://github.com/getwud/wud/releases
  whats-up-docker:
    image: ghcr.io/getwud/wud:8.2.2
    container_name: whats-up-docker
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    networks:
      - docker-socket
      - glance
    environment:
      WUD_LOG_LEVEL: info
      WUD_SERVER_FEATURE_DELETE: false
      WUD_WATCHER_DOCKER_CRON: 41 2,14 * * * # Attempt to bypass TOOMANYREQUESTS for ghcr.io
      WUD_WATCHER_DOCKER_HOST: readonly-docker-socket
      WUD_WATCHER_DOCKER_PORT: 2375
      WUD_WATCHER_DOCKER_SOCKET: tcp://readonly-docker-socket
      WUD_WATCHER_DOCKER_WATCHBYDEFAULT: false
      WUD_WATCHER_DOCKER_WATCHEVENTS: false
      TZ: ${TZ:?}
    volumes:
      - ./data:/store
    labels:
      glance.name: What's Up Docker
      glance.icon: sh:wud
      glance.url: https://wud.${ROOT_DOMAIN:?}/containers?update-available=true&group-by-label=com.docker.compose.project
      glance.category: monitoring

      traefik.enable: true
      traefik.custom.host: wud
      traefik.http.routers.whats-up-docker.middlewares: authelia@file

      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
    depends_on:
      init:
        condition: service_completed_successfully

networks:
  docker-socket:
    name: docker-readonly_wud
    external: true
  glance:
    name: wud_glance
    driver_opts:
      com.docker.network.bridge.name: br-wud_glance
