services:
  init:
    image: alpine
    entrypoint: install -d -o ${NAS_UID:?} -g ${NAS_GID:?} -m 770
    volumes:
      - ${PATH_TO_MEDIA:?}:/tmp/media
    command:
      - /tmp/media/movies
      - /tmp/media/tv
      - /tmp/media/music

  # https://github.com/linuxserver/docker-jellyfin/pkgs/container/jellyfin
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin:10.10.7
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: ${NAS_UID:?}
      PGID: ${NAS_GID:?}
      TZ: ${TZ:?}
      DOCKER_MODS: linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - ${PATH_TO_ROOT:?}/jellyfin/config:/config
      - ${PATH_TO_MEDIA:?}:/data:ro
    devices:
      - /dev/dri:/dev/dri
    dns:
      - 9.9.9.9 # fuck GeoDNS
    labels:
      traefik.enable: true
      traefik.http.routers.jellyfin.entrypoints: local-secure,external-secure
      traefik.http.routers.jellyfin.rule: Host(`jellyfin.${ROOT_DOMAIN:?}`)
      traefik.http.services.jellyfin.loadbalancer.server.port: 8096
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
      wud.tag.exclude: ^2021.\d+\.\d+$$

networks:
  proxy:
    external: true
