services:
  # https://hub.docker.com/r/amir20/dozzle/tags
  dozzle:
    image: amir20/dozzle:v8.13.1
    container_name: dozzle
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    networks:
      - proxy
      - readonly-docker-socket
    environment:
      DOZZLE_NO_ANALYTICS: true
      DOZZLE_REMOTE_HOST: tcp://readonly-docker-socket:2375
    volumes:
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$

networks:
  proxy:
    external: true
  readonly-docker-socket:
    external: true
