services:
  # https://hub.docker.com/r/amir20/dozzle/tags
  dozzle:
    image: amir20/dozzle:v8.12.0
    container_name: dozzle
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  proxy:
    external: true
