services:
  # https://hub.docker.com/r/amir20/dozzle/tags
  dozzle:
    image: amir20/dozzle:v8.12.0
    container_name: dozzle
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.entrypoints=local-secure
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${ROOT_DOMAIN:?}`)
      - traefik.http.services.dozzle.loadbalancer.server.port=8080

networks:
  proxy:
    external: true
