apiVersion: 1

datasources:
  - name: InfluxDB v2 (InfluxQL)
    type: influxdb
    uid: influxdb_v2_influxql
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: InfluxQL
      dbName: ${INFLUXDB_BUCKET}
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Token ${INFLUXDB_ADMIN_TOKEN}
