services:
  # https://hub.docker.com/r/henrygd/beszel/tags
  beszel:
    image: henrygd/beszel:0.10.2
    container_name: beszel
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - ${PATH_TO_ROOT:?}/beszel/data:/beszel_data
      - ${PATH_TO_ROOT:?}/beszel/socket:/beszel_socket
      - /etc/localtime:/etc/localtime:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.beszel.entrypoints=local-secure
      - traefik.http.routers.beszel.rule=Host(`beszel.${ROOT_DOMAIN:?}`)
      - traefik.http.services.beszel.loadbalancer.server.port=8090
    depends_on:
      beszel-agent:
        condition: service_healthy

  # https://hub.docker.com/r/henrygd/beszel-agent/tags
  beszel-agent:
    image: henrygd/beszel-agent:0.10.2
    container_name: beszel_agent
    restart: unless-stopped
    network_mode: host
    environment:
      LISTEN: /beszel_socket/beszel.sock
      KEY: ${KEY:?}
    volumes:
      - ${PATH_TO_ROOT:?}/beszel/socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "/agent", "health"]
      start_period: 5s
      interval: 120s

networks:
  proxy:
    external: true
