- Media:
  - Jellyfin:
      icon: jellyfin.svg
      href: https://jellyfin.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: The Free Software Media System

  - Audiobookshelf:
      icon: audiobookshelf.svg
      href: https://audiobookshelf.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: Self-hosted audiobook and podcast server

- Media Management:
  - Radarr:
      icon: radarr.svg
      href: https://radarr.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: Movie collection manager

  - Sonarr:
      icon: sonarr.svg
      href: https://sonarr.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: TV shows collection manager

  - Lidarr:
      icon: lidarr.svg
      href: https://lidarr.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: Music collection manager

  - Prowlarr:
      icon: prowlarr.svg
      href: https://prowlarr.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: Indexer manager/proxy

  - qBittorrent:
      icon: qbittorrent.svg
      href: https://qbittorrent.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: BitTorrent client

- Files:
  - Nextcloud:
      icon: nextcloud-white.svg
      href: https://nextcloud.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: Open source content collaboration platform

  - Filebrowser:
      icon: filebrowser.svg
      href: https://filebrowser.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: Web File Browser

- Admin:
  - Traefik:
      icon: traefik.svg
      description: The Cloud Native Application Proxy
      href: https://traefik.{{HOMEPAGE_VAR_ROOT_DOMAIN}}

  - Dozzle:
      icon: dozzle.svg
      href: https://dozzle.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: Simple Container Monitoring and Logging

  - Grafana:
      icon: grafana.svg
      href: https://grafana.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
      description: The open and composable observability platform

- Monitoring:
  - Uptime:
      id: monitoring_uptime
      widget:
        type: iframe
        src: https://grafana.{{HOMEPAGE_VAR_ROOT_DOMAIN}}/d-solo/aek2tmxcsptz4f/system?refresh=10s&panelId=1&__feature.dashboardSceneSolo

  - CPU usage:
      id: monitoring_cpu
      widget:
        type: iframe
        src: https://grafana.{{HOMEPAGE_VAR_ROOT_DOMAIN}}/d-solo/aek2tmxcsptz4f/system?refresh=10s&panelId=2&__feature.dashboardSceneSolo

  - RAM usage:
      id: monitoring_ram
      widget:
        type: iframe
        src: https://grafana.{{HOMEPAGE_VAR_ROOT_DOMAIN}}/d-solo/aek2tmxcsptz4f/system?refresh=10s&panelId=3&__feature.dashboardSceneSolo

  - Disks usage:
      id: monitoring_disks
      widget:
        type: iframe
        src: https://grafana.{{HOMEPAGE_VAR_ROOT_DOMAIN}}/d-solo/aek2tmxcsptz4f/system?refresh=10s&panelId=9&__feature.dashboardSceneSolo
