- Files & Media:
    - Jellyfin:
        icon: jellyfin.svg
        href: https://jellyfin.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: The Free Software Media System
        server: docker
        container: jellyfin

    - Audiobookshelf:
        icon: audiobookshelf.svg
        href: https://audiobookshelf.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Self-hosted audiobook and podcast server
        server: docker
        container: audiobookshelf

    - Nextcloud:
        icon: nextcloud-white.svg
        href: https://nextcloud.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Open source content collaboration platform
        server: docker
        container: nextcloud

    - Immich:
        icon: immich.svg
        href: https://immich.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Self-hosted photo and video management solution
        server: docker
        container: immich

    - Filebrowser:
        icon: filebrowser.svg
        href: https://filebrowser.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Web File Browser
        server: docker
        container: filebrowser

- Media Management:
    - Prowlarr:
        icon: prowlarr.svg
        href: https://prowlarr.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Indexer manager/proxy
        server: docker
        container: torrent_prowlarr

    - qBittorrent:
        icon: qbittorrent.svg
        href: https://qbittorrent.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: BitTorrent client
        server: docker
        container: torrent_qbittorrent

    - MusicBrainz Picard:
        icon: musicbrainz.svg
        href: https://picard.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Music tagger powered by the MusicBrainz database
        server: docker
        container: picard

    - MeTube:
        icon: metube.svg
        href: https://metube.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Self-hosted YouTube downloader
        server: docker
        container: metube

- Admin:
    - Cockpit:
        icon: cockpit-light.svg
        href: https://cockpit.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: A web-based graphical interface for servers

    - Dockge:
        icon: dockge.svg
        href: https://dockge.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: A fancy, easy-to-use and reactive self-hosted docker compose.yaml stack-oriented manager
        server: docker
        container: dockge

    - AdGuard Home:
        icon: adguard-home.svg
        href: https://adguard.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Network-wide ads & trackers blocking DNS server
        server: docker
        container: adguard

    - Dozzle:
        icon: dozzle.svg
        href: https://dozzle.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Simple Container Monitoring and Logging
        server: docker
        container: dozzle

    - Traefik:
        icon: traefik.svg
        description: The Cloud Native Application Proxy
        href: https://traefik.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        server: docker
        container: traefik

    - What's Up Docker:
        icon: sh-wud.svg
        href: https://wud.{{HOMEPAGE_VAR_ROOT_DOMAIN}}/containers?update-available=true&group-by-label=com.docker.compose.project
        description: Keep your containers up-to-date!
        server: docker
        container: whats-up-docker
        widget:
          type: whatsupdocker
          url: https://wud.{{HOMEPAGE_VAR_ROOT_DOMAIN}}

    - DbGate:
        icon: sh-dbgate.webp
        href: https://dbgate.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
        description: Database manager for MySQL, PostgreSQL, SQL Server, MongoDB, SQLite and others
        server: docker
        container: dbgate

- Monitoring:
    - Monitoring_Services:
        - Grafana:
            icon: grafana.svg
            href: https://grafana.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
            description: The open and composable observability platform
            server: docker
            container: monitoring_grafana

        - Uptime Kuma:
            icon: uptime-kuma.svg
            href: https://uptime-kuma.{{HOMEPAGE_VAR_ROOT_DOMAIN}}
            description: Easy-to-use self-hosted monitoring tool
            server: docker
            container: uptime-kuma

    - Monitoring_Grafana:
        - Uptime:
            id: monitoring_uptime
            widget:
              type: iframe
              src: https://grafana.{{HOMEPAGE_VAR_ROOT_DOMAIN}}/d-solo/aek2tmxcsptz4f/system?refresh=10s&panelId=1&__feature.dashboardSceneSolo

        - CPU usage:
            id: monitoring_cpu
            widget:
              type: iframe
              src: https://grafana.{{HOMEPAGE_VAR_ROOT_DOMAIN}}/d-solo/aek2tmxcsptz4f/system?refresh=10s&panelId=2&__feature.dashboardSceneSolo

        - RAM usage:
            id: monitoring_ram
            widget:
              type: iframe
              src: https://grafana.{{HOMEPAGE_VAR_ROOT_DOMAIN}}/d-solo/aek2tmxcsptz4f/system?refresh=10s&panelId=3&__feature.dashboardSceneSolo

        - Disks usage:
            id: monitoring_disks
            widget:
              type: iframe
              src: https://grafana.{{HOMEPAGE_VAR_ROOT_DOMAIN}}/d-solo/aek2tmxcsptz4f/system?refresh=10s&panelId=9&__feature.dashboardSceneSolo
