title: My NAS
theme: dark
color: slate
background:
  image: /images/background.jpg
  blur: sm
headerStyle: underlined
disableCollapse: true
iconStyle: theme
useEqualHeights: true

layout:
  Group A:
    style: row
    columns: 2
    header: false
    Media:
      style: row
      columns: 2
      icon: mdi-multimedia
    Files:
      style: row
      columns: 2
      icon: mdi-cloud-check-variant
  Media Management:
    style: row
    columns: 5
    icon: mdi-play-network
  Admin:
    style: row
    columns: 4
    icon: mdi-security
  Monitoring:
    style: row
    columns: 4
    icon: mdi-chart-line-stacked
