title: My Home Lab
theme: dark
color: slate
background:
  image: /images/background.jpg
  blur: sm
headerStyle: clean
disableCollapse: true
iconStyle: theme
useEqualHeights: true

layout:
  Files & Media:
    icon: mdi-multimedia
    style: row
    columns: 5
  Media Management:
    style: row
    columns: 4
    icon: mdi-play-network
  Admin:
    style: row
    columns: 3
    icon: mdi-security
  Monitoring:
    style: column
    icon: mdi-chart-line-stacked
    Monitoring_Services:
      header: false
      style: row
      columns: 4
    Monitoring_Grafana:
      header: false
      style: row
      columns: 4
