services:
  init:
    image: alpine
    entrypoint: install -d -o ${NAS_UID:?} -g ${NAS_GID:?} -m 770
    volumes:
      - ${PATH_TO_MEDIA:?}:/tmp/media
    command:
      - /tmp/media
      - /tmp/media/downloads

  # https://github.com/linuxserver/docker-prowlarr/pkgs/container/prowlarr
  # https://github.com/linuxserver/docker-prowlarr/releases
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.37.0
    container_name: torrent_prowlarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: ${NAS_UID:?}
      PGID: ${NAS_GID:?}
      TZ: ${TZ:?}
    volumes:
      - ./prowlarr:/config
    labels:
      traefik.enable: true
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
    depends_on:
      qbittorrent:
        condition: service_started

  # https://github.com/linuxserver/docker-qbittorrent/pkgs/container/qbittorrent
  # https://github.com/linuxserver/docker-qbittorrent/releases
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:5.1.2
    container_name: torrent_qbittorrent
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: ${NAS_UID:?}
      PGID: ${NAS_GID:?}
      TZ: ${TZ:?}
      WEBUI_PORT: 8080
      # https://github.com/vuetorrent/VueTorrent/pkgs/container/vuetorrent-lsio-mod
      # https://github.com/VueTorrent/VueTorrent/releases
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:2.27.0
    volumes:
      - ./qbittorrent:/config
      - ./modcache:/modcache
      - ${PATH_TO_MEDIA:?}/downloads:/downloads
    labels:
      traefik.enable: true
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
      wud.tag.exclude: ^20.04.1|14.3.9$$
    depends_on:
      init:
        condition: service_completed_successfully

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: br-${COMPOSE_PROJECT_NAME:?}
  proxy:
    external: true
