services:
  init:
    image: alpine
    entrypoint: install -d -o ${NAS_UID:?} -g ${NAS_GID:?} -m 770
    volumes:
      - ${PATH_TO_MEDIA:?}:/tmp/media
    command:
      - /tmp/media/movies
      - /tmp/media/tv
      - /tmp/media/music
      - /tmp/media/downloads

  # https://github.com/linuxserver/docker-prowlarr/pkgs/container/prowlarr
  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:1.35.1
    container_name: torrent_prowlarr
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: ${NAS_UID:?}
      PGID: ${NAS_GID:?}
      TZ: ${TZ:?}
    volumes:
      - ${PATH_TO_ROOT:?}/torrent/prowlarr:/config
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.entrypoints: local-secure
      traefik.http.routers.prowlarr.rule: Host(`prowlarr.${ROOT_DOMAIN:?}`)
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$

  # https://github.com/linuxserver/docker-qbittorrent/pkgs/container/qbittorrent
  # https://github.com/vuetorrent/VueTorrent/pkgs/container/vuetorrent-lsio-mod
  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:5.1.0
    container_name: torrent_qbittorrent
    restart: unless-stopped
    networks:
      - proxy
    environment:
      PUID: ${NAS_UID:?}
      PGID: ${NAS_GID:?}
      TZ: ${TZ:?}
      WEBUI_PORT: 8080
      DOCKER_MODS: ghcr.io/vuetorrent/vuetorrent-lsio-mod:2.24.2
    volumes:
      - ${PATH_TO_ROOT:?}/torrent/qbittorrent:/config
      - ${PATH_TO_MEDIA:?}/downloads:/data/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.qbittorrent.entrypoints: local-secure
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent.${ROOT_DOMAIN:?}`)
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$
      wud.tag.exclude: ^20.04.1|14.3.9$$
    depends_on:
      init:
        condition: service_completed_successfully

networks:
  default:
    driver_opts:
      com.docker.network.bridge.name: br-${COMPOSE_PROJECT_NAME:?}
  proxy:
    external: true
