services:
  # https://hub.docker.com/r/glanceapp/glance/tags
  # https://github.com/glanceapp/glance/releases
  glance:
    image: glanceapp/glance:v0.8.4
    container_name: glance
    restart: unless-stopped
    user: ${NAS_UID:?}:${NAS_GID:?}
    networks:
      - proxy
      - readonly-docker-socket
    environment:
      ADGUARD_URL: http://adguard
      ADGUARD_USERNAME: ${ADGUARD_USERNAME:?}
      ADGUARD_PASSWORD: ${ADGUARD_PASSWORD:?}
      WEATHER_LOCATION: ${WEATHER_LOCATION:?}
      WUD_URL: http://whats-up-docker:3000
    volumes:
      - ./config:/app/config:ro
      - /etc/localtime:/etc/localtime:ro
    labels:
      traefik.enable: true
      wud.watch: true
      wud.watch.digest: true
      wud.tag.include: ^v?\d+\.\d+\.\d+$$

networks:
  proxy:
    external: true
  readonly-docker-socket:
    external: true
